In [1]:
import pandas as pd
from prophet import Prophet
import matplotlib.pyplot as plt

df = pd.read_csv("incident records.csv")

df.head()

,iyear,imonth,iday,region_txt,country_txt,latitude,longitude,nwound,nkill
0,2000,1,1,North America,United States,44.405705,-85.714454,0.0,0.0
1,2000,1,2,South America,Colombia,4.667128,-74.106056,0.0,0.0
2,2000,1,2,South America,Colombia,7.198606,-75.341218,0.0,0.0
3,2000,1,3,North America,United States,38.232471,-122.644448,0.0,0.0
4,2000,1,3,North America,United States,39.103175,-84.511981,0.0,0.0

In [2]:
df_cleaned = df.drop(columns=["latitude", "longitude"])

df_cleaned

      iyear  imonth  iday     region_txt    country_txt  nwound  nkill
0      2000       1     1  North America  United States     0.0    0.0
1      2000       1     2  South America       Colombia     0.0    0.0
2      2000       1     2  South America       Colombia     0.0    0.0
3      2000       1     3  North America  United States     0.0    0.0
4      2000       1     3  North America  United States     0.0    0.0
...     ...     ...   ...            ...            ...     ...    ...
2992   2017      12    19  North America         Mexico     0.0    1.0
2993   2017      12    20  South America       Colombia     0.0    1.0
2994   2017      12    22  North America  United States     0.0    0.0
2995   2017      12    22  North America  United States     1.0    1.0
2996   2017      12    24  South America       Colombia     0.0    1.0

[2997 rows x 7 columns]

In [3]:
yearly = df.groupby("iyear").size().reset_index(name="incidents")

df_cleaned["iday"] = df_cleaned[df_cleaned["iday"]== 0] = 1

df_cleaned["date"] = df_cleaned["iyear"].astype(str) + "-" + df_cleaned["imonth"].astype(str) + "-" + df_cleaned["iday"].astype(str)  

df_cleaned["date"] = pd.to_datetime(df_cleaned["date"], errors="coerce")

In [4]:
prophet_df = pd.DataFrame({
    "ds": df_cleaned["date"],
    "y": yearly["incidents"]
})

In [5]:
model = Prophet()
model.fit(prophet_df)

future = model.make_future_dataframe(periods=24, freq="MS")

forcast = model.predict(future)

15:00:18 - cmdstanpy - INFO - Chain [1] start processing
15:00:18 - cmdstanpy - INFO - Chain [1] done processing
15:00:18 - cmdstanpy - ERROR - Chain [1] error: code '1' Operation not permitted

RuntimeError: Error during optimization! Command 'C:\Users\Brian\anaconda3\envs\prophet\Lib\site-packages\prophet\stan_model\prophet_model.bin random seed=57774 data file=C:\Users\Brian\AppData\Local\Temp\tmp6n6jmjcg\25f5vst7.json init=C:\Users\Brian\AppData\Local\Temp\tmp6n6jmjcg\nt9gbky6.json output file=C:\Users\Brian\AppData\Local\Temp\tmp6n6jmjcg\prophet_modelnncb1fxb\prophet_model-20260709150018.csv method=optimize algorithm=newton iter=10000' failed: console log output:

method = optimize
  optimize
    algorithm = newton
      newton
    jacobian = false (Default)
    iter = 10000
    save_iterations = false (Default)
id = 1 (Default)
data
  file = C:\Users\Brian\AppData\Local\Temp\tmp6n6jmjcg\25f5vst7.json
init = C:\Users\Brian\AppData\Local\Temp\tmp6n6jmjcg\nt9gbky6.json
random
  seed = 57774
output
  file = C:\Users\Brian\AppData\Local\Temp\tmp6n6jmjcg\prophet_modelnncb1fxb\prophet_model-20260709150018.csv
  diagnostic_file =  (Default)
  refresh = 100 (Default)
  sig_figs = 8 (Default)
  profile_file = profile.csv (Default)
  save_cmdstan_config = false (Default)
num_threads = 1 (Default)

Rejecting initial value:
  Error evaluating the log probability at the initial value.
Exception: normal_lpdf: Random variable is nan, but must be not nan! (in 'prophet.stan', line 130, column 2 to column 19)

User-specified initialization failed.
 Try specifying new initial values, using partially specialized initialization, reducing the range of constrained values, or reparameterizing the model.
Initialization failed.